// Query Only
$query_rsQueryJob = sprintf("SELECT jp_employer.emp_name,   jp_employer.emp_address,   jp_employer.emp_email,   jp_employer.emp_web,   jp_employer.emp_tel,   jp_ads.*,   jp_industry.indus_name,   jp_location.location_name,   jp_ads.ads_title As ads_title1 FROM jp_ads Inner Join   jp_employer On jp_ads.emp_id_fk = jp_employer.emp_id Inner Join   jp_industry On jp_ads.ads_industry_id_fk = jp_industry.indus_id Inner Join   jp_location On jp_ads.ads_location = jp_location.location_id WHERE (jp_ads.ads_title  Like %s OR   jp_ads.ads_details Like %s) And jp_ads.ads_enable_view = 1", GetSQLValueString("%" . $colname_rsQueryJob . "%", "text"),GetSQLValueString("%" . $colname_rsQueryJob . "%", "text"));

// Query and industries
$query_rsQueryJob = sprintf("Select   jp_employer.emp_name,   jp_employer.emp_address,   jp_employer.emp_email,   jp_employer.emp_web,   jp_employer.emp_tel,   jp_ads.*,   jp_industry.indus_name,   jp_location.location_name,   jp_ads.ads_title As ads_title1,   jp_ads.ads_industry_id_fk As ads_industry_id_fk1 From   jp_ads Inner Join   jp_employer On jp_ads.emp_id_fk = jp_employer.emp_id Inner Join   jp_industry On jp_ads.ads_industry_id_fk = jp_industry.indus_id Inner Join   jp_location On jp_ads.ads_location = jp_location.location_id Where   (jp_ads.ads_title Like %s Or     jp_ads.ads_details Like %s) And   jp_ads.ads_industry_id_fk = %s And   jp_ads.ads_enable_view = 1", GetSQLValueString("%" . $colname_rsQueryJob . "%", "text"),GetSQLValueString("%" . $colname_rsQueryJob . "%", "text"),GetSQLValueString($industry_rsQueryJob, "int"));


// Query, industries and location
$query_rsQueryJob = sprintf("SELECT jp_employer.emp_name,   jp_employer.emp_address,   jp_employer.emp_email,   jp_employer.emp_web,   jp_employer.emp_tel,   jp_ads.*,   jp_industry.indus_name,   jp_location.location_name,   jp_ads.ads_title As ads_title1,   jp_ads.ads_industry_id_fk As ads_industry_id_fk1 FROM jp_ads Inner Join   jp_employer On jp_ads.emp_id_fk = jp_employer.emp_id Inner Join   jp_industry On jp_ads.ads_industry_id_fk = jp_industry.indus_id Inner Join   jp_location On jp_ads.ads_location = jp_location.location_id WHERE (jp_ads.ads_title Like %s Or     jp_ads.ads_details Like %s) And   jp_ads.ads_industry_id_fk = %s And   jp_ads.ads_location = %s And  jp_ads.ads_enable_view = 1", GetSQLValueString("%" . $colname_rsQueryJob . "%", "text"),GetSQLValueString("%" . $colname_rsQueryJob . "%", "text"),GetSQLValueString($industry_rsQueryJob, "int"),GetSQLValueString($location_rsQueryJob, "int"));

// Query, industries, location, and salaries
$query_rsQueryJob = sprintf("SELECT jp_employer.emp_name,   jp_employer.emp_address,   jp_employer.emp_email,   jp_employer.emp_web,   jp_employer.emp_tel,   jp_ads.*,   jp_industry.indus_name,   jp_location.location_name,   jp_ads.ads_title As ads_title1,   jp_ads.ads_industry_id_fk As ads_industry_id_fk1 FROM jp_ads Inner Join   jp_employer On jp_ads.emp_id_fk = jp_employer.emp_id Inner Join   jp_industry On jp_ads.ads_industry_id_fk = jp_industry.indus_id Inner Join   jp_location On jp_ads.ads_location = jp_location.location_id WHERE (jp_ads.ads_title Like %s Or     jp_ads.ads_details Like %s) And   jp_ads.ads_industry_id_fk = %s And   jp_ads.ads_location = %s And  jp_ads.ads_salary <= %s And jp_ads.ads_enable_view = 1", GetSQLValueString("%" . $colname_rsQueryJob . "%", "text"),GetSQLValueString("%" . $colname_rsQueryJob . "%", "text"),GetSQLValueString($industry_rsQueryJob, "int"),GetSQLValueString($location_rsQueryJob, "int"),GetSQLValueString($salarys_rsQueryJob, "int"));

// Query, industries, location, salaries, and experience
$query_rsQueryJob = sprintf("SELECT jp_employer.emp_name,   jp_employer.emp_address,   jp_employer.emp_email,   jp_employer.emp_web,   jp_employer.emp_tel,   jp_ads.*,   jp_industry.indus_name,   jp_location.location_name,   jp_ads.ads_title As ads_title1,   jp_ads.ads_industry_id_fk As ads_industry_id_fk1 FROM jp_ads Inner Join   jp_employer On jp_ads.emp_id_fk = jp_employer.emp_id Inner Join   jp_industry On jp_ads.ads_industry_id_fk = jp_industry.indus_id Inner Join   jp_location On jp_ads.ads_location = jp_location.location_id WHERE (jp_ads.ads_title Like %s Or     jp_ads.ads_details Like %s) And   jp_ads.ads_industry_id_fk = %s And   jp_ads.ads_location = %s And jp_ads.ads_salary <= %s And jp_ads.ads_y_exp = %s And  jp_ads.ads_enable_view = 1", GetSQLValueString("%" . $colname_rsQueryJob . "%", "text"),GetSQLValueString("%" . $colname_rsQueryJob . "%", "text"),GetSQLValueString($industry_rsQueryJob, "int"),GetSQLValueString($location_rsQueryJob, "int"),GetSQLValueString($salaries_rsQueryJob, "int"),GetSQLValueString($exp_rsQueryJob, "int"));


// 2 parameter only
// Query and locations
$query_rsQueryJob = sprintf("SELECT jp_employer.emp_name,   jp_employer.emp_address,   jp_employer.emp_email,   jp_employer.emp_web,   jp_employer.emp_tel,   jp_ads.*,   jp_industry.indus_name,   jp_location.location_name,   jp_ads.ads_title As ads_title1,   jp_ads.ads_industry_id_fk As ads_industry_id_fk1 FROM jp_ads Inner Join   jp_employer On jp_ads.emp_id_fk = jp_employer.emp_id Inner Join   jp_industry On jp_ads.ads_industry_id_fk = jp_industry.indus_id Inner Join   jp_location On jp_ads.ads_location = jp_location.location_id WHERE (jp_ads.ads_title Like %s Or     jp_ads.ads_details Like %s) And   jp_ads.ads_location = %s And  jp_ads.ads_enable_view = 1", GetSQLValueString("%" . $colname_rsQueryJob . "%", "text"),GetSQLValueString("%" . $colname_rsQueryJob . "%", "text"),GetSQLValueString($location_rsQueryJob, "int"));

// Query and Salaries
$query_rsQueryJob = sprintf("SELECT jp_employer.emp_name,   jp_employer.emp_address,   jp_employer.emp_email,   jp_employer.emp_web,   jp_employer.emp_tel,   jp_ads.*,   jp_industry.indus_name,   jp_location.location_name,   jp_ads.ads_title As ads_title1,   jp_ads.ads_industry_id_fk As ads_industry_id_fk1 FROM jp_ads Inner Join   jp_employer On jp_ads.emp_id_fk = jp_employer.emp_id Inner Join   jp_industry On jp_ads.ads_industry_id_fk = jp_industry.indus_id Inner Join   jp_location On jp_ads.ads_location = jp_location.location_id WHERE (jp_ads.ads_title Like %s Or jp_ads.ads_details Like %s) And  jp_ads.ads_salary <= %s And  jp_ads.ads_enable_view = 1", GetSQLValueString("%" . $colname_rsQueryJob . "%", "text"),GetSQLValueString("%" . $colname_rsQueryJob . "%", "text"),GetSQLValueString($salaries_rsQueryJob, "int"));

// Query and Experience
$query_rsQueryJob = sprintf("SELECT jp_employer.emp_name,   jp_employer.emp_address,   jp_employer.emp_email,   jp_employer.emp_web,   jp_employer.emp_tel,   jp_ads.*,   jp_industry.indus_name,   jp_location.location_name,   jp_ads.ads_title As ads_title1,   jp_ads.ads_industry_id_fk As ads_industry_id_fk1 FROM jp_ads Inner Join   jp_employer On jp_ads.emp_id_fk = jp_employer.emp_id Inner Join   jp_industry On jp_ads.ads_industry_id_fk = jp_industry.indus_id Inner Join   jp_location On jp_ads.ads_location = jp_location.location_id WHERE (jp_ads.ads_title Like %s Or jp_ads.ads_details Like %s) And  jp_ads.ads_y_exp = %s And  jp_ads.ads_enable_view = 1", GetSQLValueString("%" . $colname_rsQueryJob . "%", "text"),GetSQLValueString("%" . $colname_rsQueryJob . "%", "text"),GetSQLValueString($exp_rsQueryJob, "int"));


// Query, Industries and Exp
$query_rsQueryJob = sprintf("SELECT jp_employer.emp_name,   jp_employer.emp_address,   jp_employer.emp_email,   jp_employer.emp_web,   jp_employer.emp_tel,   jp_ads.*,   jp_industry.indus_name,   jp_location.location_name,   jp_ads.ads_title As ads_title1,   jp_ads.ads_industry_id_fk As ads_industry_id_fk1 FROM jp_ads Inner Join   jp_employer On jp_ads.emp_id_fk = jp_employer.emp_id Inner Join   jp_industry On jp_ads.ads_industry_id_fk = jp_industry.indus_id Inner Join   jp_location On jp_ads.ads_location = jp_location.location_id WHERE (jp_ads.ads_title Like %s Or jp_ads.ads_details Like %s) And jp_ads.ads_industry_id_fk = %s And  jp_ads.ads_y_exp = %s And  jp_ads.ads_enable_view = 1", GetSQLValueString("%" . $colname_rsQueryJob . "%", "text"),GetSQLValueString("%" . $colname_rsQueryJob . "%", "text"),GetSQLValueString($industry_rsQueryJob, "int"),GetSQLValueString($exp_rsQueryJob, "int"));

// Query, Location and salaries
$query_rsQueryJob = sprintf("SELECT jp_employer.emp_name,   jp_employer.emp_address,   jp_employer.emp_email,   jp_employer.emp_web,   jp_employer.emp_tel,   jp_ads.*,   jp_industry.indus_name,   jp_location.location_name,   jp_ads.ads_title As ads_title1,   jp_ads.ads_industry_id_fk As ads_industry_id_fk1 FROM jp_ads Inner Join   jp_employer On jp_ads.emp_id_fk = jp_employer.emp_id Inner Join   jp_industry On jp_ads.ads_industry_id_fk = jp_industry.indus_id Inner Join   jp_location On jp_ads.ads_location = jp_location.location_id WHERE (jp_ads.ads_title Like %s Or jp_ads.ads_details Like %s) And jp_ads.ads_location = %s And  jp_ads.ads_salary <= %s And  jp_ads.ads_enable_view = 1", GetSQLValueString("%" . $colname_rsQueryJob . "%", "text"),GetSQLValueString("%" . $colname_rsQueryJob . "%", "text"),GetSQLValueString($location_rsQueryJob, "int"),GetSQLValueString($salaries_rsQueryJob, "int"));

// Query, Industry and salaries
$query_rsQueryJob = sprintf("SELECT jp_employer.emp_name,   jp_employer.emp_address,   jp_employer.emp_email,   jp_employer.emp_web,   jp_employer.emp_tel,   jp_ads.*,   jp_industry.indus_name,   jp_location.location_name,   jp_ads.ads_title As ads_title1,   jp_ads.ads_industry_id_fk As ads_industry_id_fk1 FROM jp_ads Inner Join   jp_employer On jp_ads.emp_id_fk = jp_employer.emp_id Inner Join   jp_industry On jp_ads.ads_industry_id_fk = jp_industry.indus_id Inner Join   jp_location On jp_ads.ads_location = jp_location.location_id WHERE (jp_ads.ads_title Like %s Or jp_ads.ads_details Like %s) And jp_ads.ads_industry_id_fk = %s And  jp_ads.ads_salary <= %s And  jp_ads.ads_enable_view = 1", GetSQLValueString("%" . $colname_rsQueryJob . "%", "text"),GetSQLValueString("%" . $colname_rsQueryJob . "%", "text"),GetSQLValueString($industry_rsQueryJob, "int"),GetSQLValueString($salaries_rsQueryJob, "int"));


// Query, Salaries, Exp
$query_rsQueryJob = sprintf("SELECT jp_employer.emp_name,   jp_employer.emp_address,   jp_employer.emp_email,   jp_employer.emp_web,   jp_employer.emp_tel,   jp_ads.*,   jp_industry.indus_name,   jp_location.location_name,   jp_ads.ads_title As ads_title1,   jp_ads.ads_industry_id_fk As ads_industry_id_fk1 FROM jp_ads Inner Join   jp_employer On jp_ads.emp_id_fk = jp_employer.emp_id Inner Join   jp_industry On jp_ads.ads_industry_id_fk = jp_industry.indus_id Inner Join   jp_location On jp_ads.ads_location = jp_location.location_id WHERE (jp_ads.ads_title Like %s Or jp_ads.ads_details Like %s) And jp_ads.ads_y_exp = %s And  jp_ads.ads_salary <= %s And  jp_ads.ads_enable_view = 1", GetSQLValueString("%" . $colname_rsQueryJob . "%", "text"),GetSQLValueString("%" . $colname_rsQueryJob . "%", "text"),GetSQLValueString($exp_rsQueryJob, "int"),GetSQLValueString($salaries_rsQueryJob, "int"));